apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dql2dwv8g-python-gitops
  description: This is GitOps manifest for dql2dwv8g-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: dql2dwv8g-python
    backstage.io/kubernetes-id: dql2dwv8g-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: dql2dwv8g-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:dql2dwv8g-python
